#!/usr/bin/env bash
# CI/CD Setup Quick Start

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "GITHUB ACTIONS CI/CD SETUP - QUICK START"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ What's Been Set Up:"
echo ""
echo "Workflows Created:"
echo "  📄 .github/workflows/ci-fast.yml       - Lint on every push (~2 min)"
echo "  📄 .github/workflows/ci-full.yml       - Phase 3 tests on PR/main (~10 min)"
echo "  📄 .github/workflows/coverage.yml      - Coverage tracking (~2 min)"
echo ""
echo "Configuration Files:"
echo "  ⚙️  apps/api/pytest.ini                - Pytest configuration"
echo "  ⚙️  apps/api/pyproject.toml            - Coverage & pytest settings"
echo "  🔐 .gitignore                         - Environment files excluded"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 TO ACTIVATE CI/CD:"
echo ""
echo "1. Push this code to GitHub:"
echo "   git push origin main"
echo ""
echo "2. Go to GitHub Repo Settings → Secrets and variables → Actions"
echo ""
echo "3. Add these optional secrets:"
echo "   • CODECOV_TOKEN (from https://codecov.io)"
echo "   • ANTHROPIC_API_KEY (for optional features)"
echo ""
echo "4. Go to Settings → Branches → main → Add protection rules:"
echo "   • Require status checks before merging"
echo "   • Select: 'ci-full / integration-tests'"
echo ""
echo "5. Create a test branch and open a PR:"
echo "   git checkout -b test/ci-setup"
echo "   git push origin test/ci-setup"
echo "   # Open PR on GitHub"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 PIPELINE OVERVIEW:"
echo ""
echo "┌─ Every Push to Any Branch"
echo "├─→ ci-fast.yml"
echo "│   ├── Lint (ruff)       ~30s"
echo "│   ├── Type check (mypy) ~30s"
echo "│   └── Format (black)    ~30s"
echo "│   Total: ~2 min ✨ FAST"
echo ""
echo "├─ PR to main / Push to main"
echo "├─→ ci-fast.yml (same as above)"
echo "└─→ ci-full.yml"
echo "    ├── Start PostgreSQL     ~30s"
echo "    ├── Run migrations       ~20s"
echo "    ├── Phase 3 tests        ~5 min"
echo "    ├── Database verify      ~30s"
echo "    ├── Coverage reports     ~30s"
echo "    └── Codecov upload       ~30s"
echo "    Total: ~10 min ⚡ COMPREHENSIVE"
echo ""
echo "└─ Merge to main"
echo "  └─→ coverage.yml"
echo "      ├── Coverage badge     ~30s"
echo "      └── Codecov update     ~30s"
echo "      Total: ~2 min 📈 TRACKING"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "💡 KEY FEATURES:"
echo ""
echo "  ✅ Automatic testing on every commit"
echo "  ✅ Real PostgreSQL database in CI"
echo "  ✅ Phase 3 integration tests run automatically"
echo "  ✅ Coverage reports generated"
echo "  ✅ Codecov integration for tracking"
echo "  ✅ Blocks PRs if tests fail"
echo "  ✅ Fast feedback on push (2 min lint)"
echo "  ✅ Full validation on PR (10 min tests)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📝 LOCAL TESTING (OPTIONAL):"
echo ""
echo "Before pushing, run locally:"
echo ""
echo "  cd apps/api"
echo ""
echo "  # Fast checks (like ci-fast)"
echo "  ruff check app/"
echo "  black --check app/"
echo "  mypy app/ --ignore-missing-imports"
echo ""
echo "  # Full tests (requires PostgreSQL running)"
echo "  pytest tests/test_integration_phase3.py -v --cov=app"
echo ""
echo "  # Verify database"
echo "  python scripts/verify_data.py"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔍 VIEWING RESULTS:"
echo ""
echo "1. GitHub Actions Tab"
echo "   Repo → Actions tab → See all workflow runs"
echo ""
echo "2. PR Checks"
echo "   PR page → Scroll to Checks section → See status"
echo ""
echo "3. Coverage Reports"
echo "   PR → Codecov comment shows coverage %"
echo "   Artifacts → coverage-report → htmlcov/index.html"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  TROUBLESHOOTING:"
echo ""
echo "Workflow not running?"
echo "  • Make sure you pushed .github/workflows/ to GitHub"
echo "  • Check Actions tab for errors"
echo "  • Branch must be main or have PR to main"
echo ""
echo "Tests failing in CI but passing locally?"
echo "  • Check DATABASE_URL environment variable"
echo "  • PostgreSQL might need different connection string"
echo "  • Run: postgresql+asyncpg://postgres:postgres@localhost:5432/evijnar_test"
echo ""
echo "Coverage not uploading?"
echo "  • Set CODECOV_TOKEN in GitHub Secrets"
echo "  • Get token from https://codecov.io/gh/your-org/Evijnar"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 FULL DOCUMENTATION:"
echo ""
echo "  Read: docs/CI_CD_SETUP.md"
echo "  Read: docs/PHASE3_TESTING.md"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
